option(COUCHBASE_CXX_CLIENT_ENABLE_BUILD_WITH_TIME_TRACE "Enable compiler time profiling/tracing flags" OFF)

if(COUCHBASE_CXX_CLIENT_ENABLE_BUILD_WITH_TIME_TRACE)
    if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
        target_compile_options(project_options INTERFACE -ftime-trace)
        message(STATUS "Clang time tracing enabled: Each compiled source file will generate a .json trace (e.g., <file>.json) in the build directory. Open these with Chrome (chrome://tracing) or Perfetto for visualization.")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(project_options INTERFACE -ftime-report)
        message(STATUS "GCC time report enabled: Compilation phase timing will be printed to the build log/console for each source file.")
    elseif(MSVC)
        target_compile_options(project_options INTERFACE /Bt+ /d2cgsummary)
        message(STATUS "MSVC build timing enabled: Compilation times per file and codegen summaries will be printed to the build log/console.")
    else()
        message(WARNING "ENABLE_BUILD_WITH_TIME_TRACE is ON, but no known tracing flags are set for this compiler (${CMAKE_CXX_COMPILER_ID}).")
    endif()
endif()
