name: linters
permissions: {}

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang_format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget gnupg2 git
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo bash -c "echo 'deb https://apt.llvm.org/noble/ llvm-toolchain-noble main' >> /etc/apt/sources.list"
          sudo apt-get update -y
          sudo apt-get install -y clang-format
      - name: Run clang-format
        run: ./bin/check-clang-format

  clang_static_analyzer:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev cmake curl wget gnupg2
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo bash -c "echo 'deb https://apt.llvm.org/noble/ llvm-toolchain-noble main' >> /etc/apt/sources.list"
          sudo apt-get update -y
          sudo apt-get install -y clang clang-tools
      - name: Run scan build
        run: ./bin/check-clang-static-analyzer
        env:
          CB_CC: /usr/bin/clang
          CB_CXX: /usr/bin/clang++-21
          CB_SCAN_BUILD: /usr/bin/scan-build-21
      - name: Upload scan-build report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: cmake-build-report.tar.gz

  cppcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev cmake curl wget gnupg2 clang clang-tools cppcheck
      - name: Run cppcheck
        run: ./bin/check-cppcheck

  clang_tidy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev cmake curl wget gnupg2 clang clang-tools clang-tidy
      - name: Run cppcheck
        run: ./bin/check-clang-tidy
